// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcTncweEKNQxi-Sd4ktCvlW5QLvPr3gSA',
    appId: '1:1071714618964:web:a7cfa9baffdc85fa7d67c1',
    messagingSenderId: '1071714618964',
    projectId: 'area-51-f2817',
    authDomain: 'area-51-f2817.firebaseapp.com',
    storageBucket: 'area-51-f2817.appspot.com',
    measurementId: 'G-1SHR8CSPG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5IstssUJCVeTD06-l_j6Qd4O5IAHNbVM',
    appId: '1:1071714618964:android:687b2ec4b354fbad7d67c1',
    messagingSenderId: '1071714618964',
    projectId: 'area-51-f2817',
    storageBucket: 'area-51-f2817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jYRqWcfOBYQD_tFJ-KS5UyZbXBEUgSw',
    appId: '1:1071714618964:ios:06c1f2dbccbb37d37d67c1',
    messagingSenderId: '1071714618964',
    projectId: 'area-51-f2817',
    storageBucket: 'area-51-f2817.appspot.com',
    iosClientId: '1071714618964-rf44jgso57e290srku1v145cl76n1gri.apps.googleusercontent.com',
    iosBundleId: 'com.example.area51',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7jYRqWcfOBYQD_tFJ-KS5UyZbXBEUgSw',
    appId: '1:1071714618964:ios:06c1f2dbccbb37d37d67c1',
    messagingSenderId: '1071714618964',
    projectId: 'area-51-f2817',
    storageBucket: 'area-51-f2817.appspot.com',
    iosClientId: '1071714618964-rf44jgso57e290srku1v145cl76n1gri.apps.googleusercontent.com',
    iosBundleId: 'com.example.area51',
  );
}
